
import { Button, GroupBox, SpinBox, ComboBox, CheckBox, LineEdit, TabWidget, VerticalBox, HorizontalBox,
    Slider, StandardTableView, SpinBox, Switch , GridBox} from "std-widgets.slint";

export struct Action  {
    type: string,
    text: string,
}
export global TableView  {
    callback sort_ascending(int);
    callback sort_descending(int);
    callback query(Action);
    
    in property <[[StandardListViewItem]]> row_data: [  
    ];

}
export component QueryPage inherits GridBox {
    // title: @tr("Query");
    VerticalBox {
        HorizontalBox {
            alignment: start;
            text-edit :=LineEdit {
                placeholder-text: @tr("Enter some text");
            }
            Button {
                text:@tr("X") ;
                clicked =>{
                    text-edit.text = ""
                }
            }
           
            mode_cb := ComboBox {
                current_index: 0;
                model: [@tr("SN"), @tr("Box"),@tr("Carton"), @tr("Worker_ID"), @tr("Date")];
                
            }
            query := Button {
                text: @tr("查询");
                // clicked => {TableView.query(text-edit.text,mode-cb.current-index)}
                clicked => {TableView.query({
                    type:mode-cb.current-value,
                    text:text-edit.text
                })}
            }

            
        }
    if mode-cb.current-index == 0 :
    StandardTableView{
        sort-ascending(index) => {
            TableView.sort_ascending(index);
        }

        sort-descending(index) => {
            TableView.sort-descending(index);
        }
        columns: [
            { title: @tr("SN") },
            { title: @tr("工号") },
            { title: @tr("料号") },
            { title: @tr("结果") },
            { title: @tr("Ith") },
            { title: @tr("Pf") },
            { title: @tr("Vop") },
            { title: @tr("Im") },
            { title: @tr("Rs") },
            { title: @tr("Sen") },
            { title: @tr("Res") },
            { title: @tr("ICC") },
            { title: @tr("Idark") },
            { title: @tr("Vbr") },
            { title: @tr("IXtalk") },
            { title: @tr("Kink") },
            { title: @tr("测试时间") },
            
        ];
        rows:TableView.row-data
        ;
    }
    if mode-cb.current-index == 1 :
    StandardTableView{
        sort-ascending(index) => {
            TableView.sort_ascending(index);
        }

        sort-descending(index) => {
            TableView.sort-descending(index);
        }
        columns: [
            { title: @tr("盒号") },
            { title: @tr("SN") },
            { title: @tr("料号") },
            { title: @tr("工单号") },
            { title: @tr("操作员") },
            { title: @tr("装盒时间") },
            
            
        ];
        rows:TableView.row-data
        ;
    }
    if mode-cb.current-index == 2 :
    StandardTableView{
        sort-ascending(index) => {
            TableView.sort_ascending(index);
        }

        sort-descending(index) => {
            TableView.sort-descending(index);
        }
        columns: [
            { title: @tr("SN") },
            { title: @tr("TestTemp") },
            { title: @tr("Ith") },
            { title: @tr("SE") },
            { title: @tr("Po") },
            { title: @tr("Vf") },
            { title: @tr("Im") },
            { title: @tr("Sen") },
            { title: @tr("Box_No") },
            { title: @tr("Carton_No") },
            
            
        ];
        rows:TableView.row-data
        ;
    }
    }
    



    
}
