import {GroupBox,ComboBox, CheckBox, LineEdit,ListView} from "std-widgets.slint";
export struct Action  {
    type: string,
    text: string,
}
export struct Infos_Box {
    box_sn: string,
    sn: string,
    pn: string,
    order: string,
    workerid: string,
    date: string,
}
export struct Infos_Sn {
    sn: string,
    productBill: string,
    testType: string,
    result: string,
    ith: string,
    pf: string,
    vop: string,
    im: string,
    rs: string,
    sen: string,
    res: string,
    icc: string,
    idark: string,
    vbr:string,
    ixtalk: string,
    kink: string,
    testdate: string,
}
export global InfosData {
    callback query(Action);
    in-out property<[Infos_Box]> datas_box;
    in-out property<[Infos_Sn]> datas_sn;
    in-out property <string> text;

}
component Button inherits Rectangle {
    in-out property text <=> txt.text;
    callback clicked <=> touch.clicked;
    border-radius: root.height * 1.05;
    // border-width: 15px;
    border-color: root.background.darker(25%);
    background: touch.pressed ? #6b8282 : touch.has-hover ? #535b97 :  #456;
    height: txt.preferred-height * 3.5;
    min-width: txt.preferred-width + 35px;
    txt := Text {
        x: (parent.width - self.width)/2 + (touch.pressed ? 15px : 0);
        y: (parent.height - self.height)/2 + (touch.pressed ? 18px : 0);
        color: touch.pressed ? #fff : #eee;
        font-size: 13px;
    }
    touch := TouchArea { }
}



export component QueryPage inherits GridLayout {
   
    VerticalLayout {
        spacing: 15px;
        HorizontalLayout {
            height: 50px;
            alignment: start;
            spacing :20px;
            text-edit :=LineEdit {
                placeholder-text: @tr("Enter some text");
                accepted => {
                    query.clicked();
                }
                horizontal-alignment:left;
                width: 350px;
                font-size: 15px;

                
                
            }
            
            Button {
                text:@tr("  X  ") ;
                clicked =>{
                    text-edit.text = ""
                }
                
            }
            
            mode_cb := ComboBox {
                current_index: 0;
                model: [@tr("SN"), @tr("Box"),@tr("Carton"), @tr("Worker_ID"), @tr("Date")];
                

            }
            query := Button {
                text: @tr(" 查询 ");
                clicked => {
                    InfosData.query({
                    type:mode-cb.current-value,
                    text:text-edit.text
                    })
                }
                
            }
        
            text := Rectangle {
                Text{
                   text : @tr("数量：{}",InfosData.text);
                   font-size: 16px;
                }
                 
                
            }
        
        }
    
    // Rectangle{
        if mode-cb.current-index == 0 :VerticalLayout{
        HorizontalLayout {
            Text {
                text: @tr("SN");
                horizontal-alignment: center;
                width: 180px;
            }
            for da in [
                // {text: @tr("SN")},
                {text: @tr("工号")},
                {text: @tr("料号")},
                {text: @tr("结果")},
                {text: @tr("Ith")},
                {text: @tr("Pf")},
                {text: @tr("Vop")},
                {text: @tr("Im")},
                {text: @tr("Rs")},
                {text: @tr("Sen")},
                {text: @tr("Res")},
                {text: @tr("ICC")},
                {text: @tr("Idark")},
                {text: @tr("Vbr")},
                {text: @tr("IXtalk")},
                {text: @tr("Kink")},
                // {text: @tr("TestDate")},
            ] : Text {
                        text: da.text;
                        horizontal-alignment: center;
                        
                    }
                
            Text {
                text: @tr("TestDate");
                horizontal-alignment: center;
                width: 200px;
            }
        }
            
        ListView {
            height: 800px;
            for data in InfosData.datas_sn: HorizontalLayout {
                    Text {
                        text: {data.sn};
                        horizontal-alignment: center;
                    }
                    Text {
                        text: {data.productBill};
                        horizontal-alignment: center;
                    }
                    Text {
                        text: {data.testType};
                        horizontal-alignment: center;
                    }
                    Text {
                        text: {data.result};
                        horizontal-alignment: center;
                    }
                    Text {
                        text: {data.ith};
                        horizontal-alignment: center;
                    }
                    Text {
                        text: {data.pf};
                        horizontal-alignment: center;
                    }
                    Text {
                        text: {data.vop};
                        horizontal-alignment: center;
                    }
                    Text {
                        text: {data.im};
                        horizontal-alignment: center;
                    }
                    Text {
                        text: {data.rs};
                        horizontal-alignment: center;
                    }
                    Text {
                        text: {data.sen};
                        horizontal-alignment: center;
                    }
                    Text {
                        text: {data.res};
                        horizontal-alignment: center;
                    }
                    Text {
                        text: {data.icc};
                        horizontal-alignment: center;
                    }
                    Text {
                        text: {data.idark};
                        horizontal-alignment: center;
                    }
                    Text {
                        text: {data.vbr};
                        horizontal-alignment: center;
                    }
                    Text {
                        text: {data.ixtalk};
                        horizontal-alignment: center;
                    }
                    Text {
                        text: {data.kink};
                        horizontal-alignment: center;
                    }
                    Text {
                        text: {data.testdate};
                        horizontal-alignment: center;
                    }
                    
                }
            }
                
            
        }
            
        
    

        if mode-cb.current-index == 1 :VerticalLayout{
        HorizontalLayout {
                        for da in [
                            {text: @tr("盒号")},
                            {text: @tr("SN")},
                            {text: @tr("料号")},
                            {text: @tr("工单号")},
                            {text: @tr("操作员")},
                            {text: @tr("装盒时间")},
                        ] : 
                                Text {
                                    text: da.text;
                                    horizontal-alignment: center;
                                    font-size: 12px;
                                    
                                }
                            
                    }
                    
        ListView {
            height: 800px;
            
            for data in InfosData.datas_box: HorizontalLayout {
                    Text {
                        text: {data.box-sn};
                        horizontal-alignment: center;
                        font-size: 12px;
                        height: 25px;
                    }
                    Text {
                        text: {data.sn};
                        horizontal-alignment: center;
                        font-size: 12px;
                        height: 25px;
                    }
                    Text {
                        text: {data.pn};
                        horizontal-alignment: center;
                        font-size: 12px;
                        height: 25px;
                    }
                    Text {
                        text: {data.order};
                        horizontal-alignment: center;
                        font-size: 12px;
                        height: 25px;
                    }
                    Text {
                        text: {data.workerid};
                        horizontal-alignment: center;
                        font-size: 12px;
                        height: 25px;
                    }
                    Text {
                        text: {data.date};
                        horizontal-alignment: center;
                        font-size: 12px;
                        height: 25px;
                    }
                }
            }
        }
    }
    

}
    // }
    