
import { SideBar} from "ui/side_bar.slint";
import { QueryPage,Action,Infos_Box,Infos_Sn,InfosData,DateTimeAdapter } from "ui/pages/query.slint";
export { QueryPage,Action,Infos_Box,Infos_Sn,InfosData,DateTimeAdapter}
export component App inherits Window {
    preferred-width: 1600px;
    preferred-height: 900px;
    title: @tr("Slint_Tools");
    HorizontalLayout {
        side-bar := SideBar {
            title: @tr("功能选择");
            model: [@tr("Menu" => "查询"), @tr("Menu" => "绑定"), @tr("Menu" => "工单"), @tr("Menu" => "TextEdit"), @tr("Menu" => "About")];
        }

        if(side-bar.current-item == 0) : QueryPage {}
        // if(side-bar.current-item == 1) : ListViewPage {}
        // if(side-bar.current-item == 2) : TableViewPage {}
        // if(side-bar.current-item == 3) : TextEditPage {}
        // if(side-bar.current-item == 4) : AboutPage {}
    }
}
